name: Deploy Javadoc

on:
  push:
    branches:
      - stable

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write 
    steps:
      - name: Deploy JavaDoc 🚀
        uses: MathieuSoysal/Javadoc-publisher.yml@v3.0.2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          javadoc-branch: gh-pages 
          java-version: 21
          target-folder: .       
          project: maven          
